Ida 159 grouped viz backend
dice-group/IDA pull request #227
Opened 2021-03-16 10:03 UTC by spoorthimadhavan

2021-03-19 10:15 UTC, spoorthimadhavan reviewed
Codacy issues

2021-03-23 09:51 UTC, nikit91 requested changes
Please add tooltip on the labels and center align the group label.

2021-05-21 07:48 UTC, nikit91 commented
@nandeeshp24 Is this ready to be merged?

2021-05-28 09:23 UTC, nikit91 approved these changes
lgtm

2021-05-28 09:23 UTC, merged