feat(ida-86): missing column values now will render with unknown value
dice-group/IDA pull request #62
Opened 2020-09-28 19:38 UTC by maqboolkhan

Missing columns values was rendering with `?`! Now will render with `unknown` column

2020-09-30 09:48 UTC, nikit91 requested changes

2020-09-30 09:48 UTC, nikit91 commented on backend-server/src/main/java/org/dice/ida/util/DbUtils.java
> +		return value.equals("?") ? "<ida-unk>" : value;
you should handle a range of values here. Including blank spaces, "?" etc. Also, please put these literals in the constants file.

2020-10-01 12:12 UTC, nikit91 commented
@nandeeshp24 Could you please implement the frontend logic for handling unknown values in this branch?

2020-10-01 16:21 UTC, nikit91 commented on backend-server/src/main/java/org/dice/ida/util/DbUtils.java
> +		return (value == null || ValidatorUtil.isStringEmpty(value) || value.equals("?")) ? IDAConst.NULL_VALUE_IDENTIFIER : value;
"?" should be in constants. All string literals that can be changed later on should be in constants

2020-10-02 08:07 UTC, maqboolkhan commented
@sourabhpoddar404 will take care of Date type column as we talked over`Element`.

2020-10-16 11:36 UTC, nikit91 approved these changes
lgtm

2020-10-16 11:36 UTC, merged