feat(Ida-98): Logging for IDA using AOP
dice-group/IDA pull request #70
Opened 2020-10-18 20:15 UTC by maqboolkhan

In this PR, Logging for IDA was introduced! AOP was used using Log4j2.

2020-10-19 08:12 UTC, nikit91 commented on backend-server/src/main/java/org/dice/ida/model/ChatMessageResponse.java
> +	}
You need to make sure that this field is written in the serialized json (ChatMsgRespSerializer.java)

2020-10-19 08:21 UTC, nikit91 commented on backend-server/src/main/java/org/dice/ida/logging/AspectLogger.java
> +		//PointCut for MessageRestController
put a debug logging statement here.

2020-10-19 08:28 UTC, nikit91 commented on backend-server/src/main/java/org/dice/ida/logging/AspectLogger.java
> +	@AfterThrowing(pointcut = "execution(* org.dice.ida.*.*.*.*(..))", throwing = "exception")
This looks like a very specific pattern and is limited by the depth. Please use something like `"execution(* org.dice.ida..*(..))"` (Ref: https://www.baeldung.com/spring-aop-pointcut-tutorial#4-args)

2020-10-19 08:31 UTC, nikit91 requested changes
The PR mostly looks good. I have mentioned a few changes, please make sure those are taken care of.

2020-10-19 12:55 UTC, nandeeshp24 commented
There seems to be some issue building the application after these changes. @maqboolkhan Please build it at your end and check before this PR gets merged

2020-10-21 19:33 UTC, maqboolkhan commented
We need to integrate the generated log file with Docker.
And also Its better not to log anything on Console on the deployment server!

So two more changes needs to be added

2020-10-30 10:29 UTC, maqboolkhan commented
1) `IDA-QA` and `IDA-PROD` Docker envs (VM) will now store logs in `~/ida-qa-logs` and `~/ida-prod-logs` folders respectively.

2) While doing development locally, if one uses Docker he/she can also find logs in `~/ida-local-logs` folder and if one using `mvn` to run IDA locally then he/she can enable console logging by uncommenting https://github.com/dice-group/IDA/blob/8eccb8254b9c4de635b384d334278147a80bbad0/backend-server/src/main/resources/log4j2.xml#L15

Note: Console logging was switched off for performance reason as IDA writes logs on file anyway!

2020-11-10 09:47 UTC, nikit91 approved these changes
lgtm

2020-11-10 09:49 UTC, merged